# Generated by Django 5.2.4 on 2025-08-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sociallinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='subheading_secondary',
            field=models.CharField(blank=True, help_text='An extra line under the main subheading, e.g., in red.', max_length=200),
        ),
    ]
