# Generated by Django 5.2.4 on 2025-09-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_nl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='heading_en',
            field=models.CharField(help_text="The main title, e.g., 'Healthy Meals, Happy Pets!'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='heading_nl',
            field=models.CharField(help_text="The main title, e.g., 'Healthy Meals, Happy Pets!'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='heading_tr',
            field=models.CharField(help_text="The main title, e.g., 'Healthy Meals, Happy Pets!'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheading_en',
            field=models.TextField(help_text='The paragraph text below the main title.', null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheading_nl',
            field=models.TextField(help_text='The paragraph text below the main title.', null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheading_secondary_en',
            field=models.CharField(blank=True, help_text='An extra line under the main subheading, e.g., in red.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheading_secondary_nl',
            field=models.CharField(blank=True, help_text='An extra line under the main subheading, e.g., in red.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheading_secondary_tr',
            field=models.CharField(blank=True, help_text='An extra line under the main subheading, e.g., in red.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheading_tr',
            field=models.TextField(help_text='The paragraph text below the main title.', null=True),
        ),
    ]
