# Generated by Django 5.2.4 on 2025-10-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_faq_answer_en_faq_answer_nl_faq_answer_tr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=22, unique=True)),
                ('pet_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(blank=True, default='instagram', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
