# Generated by Django 5.2.4 on 2025-08-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='unlimited_health',
            field=models.BooleanField(default=False, verbose_name='Unlimited Health Reports'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='unlimited_meals',
            field=models.BooleanField(default=False, verbose_name='Unlimited AI Meals'),
        ),
    ]
