# Generated by Django 5.2.4 on 2025-08-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_unlimited_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('essentials', 'Essentials'), ('wellness', 'Wellness'), ('optimal', 'Optimal')], max_length=50, unique=True),
        ),
    ]
