# Generated by Django 5.2.4 on 2025-08-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihealthreport',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
