# Generated by Django 5.2.4 on 2025-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_gender_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='neutered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
