# Generated by Django 5.2.4 on 2025-07-19 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_pet_neutered'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='age_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='age_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pettype')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.agecategory'),
        ),
    ]
