# Generated by Django 5.2.4 on 2025-07-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_breed_pet_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='food_types',
            field=models.ManyToManyField(blank=True, related_name='pets', to='pet.foodtype'),
        ),
    ]
