# Generated by Django 5.2.4 on 2025-07-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_bodytype_pet_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
