# Generated by Django 5.2.4 on 2025-07-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_activitylevel_pet_activity_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='food_allergy_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='food_allergies',
            field=models.ManyToManyField(blank=True, related_name='pets', to='pet.foodallergy'),
        ),
    ]
