# Generated by Django 5.2.4 on 2025-07-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_foodallergy_pet_food_allergy_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='health_issues',
            field=models.ManyToManyField(blank=True, related_name='pets', to='pet.healthissue'),
        ),
    ]
