# Generated by Django 5.2.4 on 2025-08-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0015_treatfrequency_pet_treat_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylevel',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='foodallergy',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='healthissue',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='activitylevel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodallergy',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthissue',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitylevel',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
