# Generated by Django 5.2.4 on 2025-08-31 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0016_alter_activitylevel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agecategory',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='agecategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order (smallest first)'),
        ),
        migrations.AlterField(
            model_name='agecategory',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_categories', to='pet.pettype'),
        ),
    ]
