# Generated by Django 5.2.4 on 2025-10-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0017_alter_agecategory_options_agecategory_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='unknown_breed',
            field=models.BooleanField(default=False, help_text='Check if breed is unknown'),
        ),
    ]
