# Generated by Django 5.2.4 on 2025-11-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0018_pet_unknown_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Calculated birth date based on age input', null=True),
        ),
    ]
