# Generated by Django 5.2.4 on 2025-11-04 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=190, unique=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=220)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, help_text='Handle or URL', max_length=120)),
                ('specializations', models.CharField(blank=True, help_text='Comma-separated (e.g., Cats, Dogs, Nutrition)', max_length=200)),
                ('working_hours', models.CharField(blank=True, help_text='e.g., Mon–Sat 09:00–18:00', max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, help_text='Account that manages this clinic page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clinics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to='vets.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='ReferredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_capture', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='NEW', max_length=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_users', to='vets.clinic')),
                ('referral_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vets.referralcode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vet_name', models.CharField(max_length=120)),
                ('degrees', models.CharField(blank=True, help_text='e.g., DVM, MSc Nutrition', max_length=200)),
                ('certifications', models.CharField(blank=True, max_length=240)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vet_profile', to='vets.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='vets_referr_code_65c42b_idx'),
        ),
        migrations.AddIndex(
            model_name='referreduser',
            index=models.Index(fields=['status', 'created_at'], name='vets_referr_status_dc2d30_idx'),
        ),
        migrations.AddIndex(
            model_name='referreduser',
            index=models.Index(fields=['clinic', 'created_at'], name='vets_referr_clinic__5aced1_idx'),
        ),
    ]
