# Generated by Django 5.2.4 on 2025-11-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='admin_approved',
            field=models.BooleanField(default=False, help_text='Approved by admin for public listing'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='email_confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text='Email address has been confirmed'),
        ),
    ]
