# Generated by Django 5.2.4 on 2025-08-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_writer',
            field=models.BooleanField(default=False, verbose_name='Writer'),
        ),
    ]
